server:
  port: 8080
  servlet:
    context-path: boot-upload

spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-request-size: -1   # 文件最大大小
      max-file-size: -1   #文件请求大小
  datasource:
    url: jdbc:mysql://localhost:3306/boot_upload?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: system

cbs:
  imagesPath: file:/D:/uploadMySQL/

